### ISSUE TITLE
NWIS Client: startDT and endDT get shifted an hour

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#107]
When retrieving data using the `nwis_client` tool, something is happening when specifying the `startDT` and `endDT` options where the returned data is shift forward in time by 1 hour. May be able to clean-up the date handling and hand-off a lot to `pandas`.

**Comment by jarq6c** [comment]
So the issue seems to be on NWIS' end. Steps to duplicate:

```python
from hydrotools.nwis_client.iv import IVDataService

# Get observed data
service = IVDataService()
observed = service.get(
    sites='01646500',
    startDT='2018-01-01',
    endDT='2019-01-01'
    )

# Check data
print(observed["value_date"].min())
print(observed["value_date"].max())
```

Output:
```console
2018-01-01 01:00:00
2019-01-01 01:00:00
```

Expected output:
```console
2018-01-01 00:00:00
2019-01-01 00:00:00
```

I checked this against NWIS directly using:
https://nwis.waterservices.usgs.gov/nwis/iv/?format=rdb&sites=01646500&startDT=2018-01-01T00:00%2b0000&endDT=2019-01-01T00:00%2b0000&parameterCd=00060&siteStatus=all

This request explicitly specifies that the timezone is +0000 (UTC) for startDt and endDt. You can see that NWIS sends back a range of data from 2018-12-31 20:00 (EST) to 2019-12-31 20:00 (EST) which is 2018-01-01 01:00 (UTC) and 2019-01-01 01:00 (UTC), respectively.

I'm not sure if this is an NWIS issue necessarily or maybe there is strange interaction due to daylight saving and I just have a naive understanding of how time works. Note that this behavior doesn't happen all the time.

@aaraney @hellkite500 @christophertubbs @james-d-brown may be interested in this behavior.

**Comment by james-d-brown** [comment]
@jarq6c 

Sounds vaguely familiar. 

Anyway, I think you're right: 2018-01-01T00:00Z is 2017-12-31T19:00-05:00 or 2017-12-31T19:00 EST, not 2017-12-31T20:00 EST.

If I'm not mistaken, we've seen something similar and asked USGS and they discovered a bug related to daylight saving for some times and/or locations. Either way, I think it's worth asking them - they are usually pretty responsive :)

**Comment by aaraney** [comment]
@jarq6c 

I remember running across this in the past and if my memory serves me right, this may be seasonal behavior -- meaning, if it is not currently daylight savings time in the U.S. the dates are correct, but I may be misremembering.

Below, i've included a script for reproducibility and a crude map that shows the spatial distribution of USGS gauge UTC time discrepancies at the turn of the 2018 new year. For simplicity, I used 'active' USGS sites included in NWM 2.1.6 in the contiguous United States spatial configuration. I fetched streamflow data for `2018-01-01`. Observations with UTC time `2018-01-01T00:00Z` were labeled `True` and all others `False`.

![distribution_of_usgs_utc_time_discrepancies](https://user-images.githubusercontent.com/39420640/127559102-9c74ffd0-92f7-44db-9dbf-6d4e64d5b9c1.png)


```python
import pandas as pd
import geopandas as gpd
from hydrotools.nwis_client import IVDataService

nwm_2_1_6_route_link_sites_url = "https://raw.githubusercontent.com/NOAA-OWP/hydrotools/main/python/gcp_client/src/hydrotools/gcp_client/data/RouteLink_CONUS_NWMv2.1.6.csv"
# data citation:
#   source: https://public.opendatasoft.com/explore/dataset/us-state-boundaries/information/
#   access date: 2021-07-29
us_boundaries_url = "https://public.opendatasoft.com/explore/dataset/us-state-boundaries/download/?format=geojson&timezone=America/New_York&lang=en"

excluded_boundaries = [
    "Alaska",
    "Hawaii",
    "Guam",
    "American Samoa",
    "Puerto Rico",
    "United States Virgin Islands",
    "Commonwealth of the Northern Mariana Islands",
]

us_boundaries = gpd.read_file(us_boundaries_url)

# filter to boundaries of interest
us_boundaries = us_boundaries[~us_boundaries["name"].isin(excluded_boundaries)]

sites = pd.read_csv(nwm_2_1_6_route_link_sites_url, comment="#")

# remove sites that have alpha characters
sites = sites[sites["usgs_site_code"].str.isdigit()]

service = IVDataService(enable_cache=False)

data = service.get(
    sites=sites.usgs_site_code,
    startDT="2018-01-01",
    endDT="2018-01-01",
    siteStatus="active",
    max_sites_per_request=100,
)

min_value_date = data.iloc[
    data.groupby("usgs_site_code").apply(lambda d: d["value_date"].idxmin())
]

min_value_date_with_metadata = min_value_date.merge(
    sites, on="usgs_site_code", how="left"
)

min_value_date_with_metadata = gpd.GeoDataFrame(
    min_value_date_with_metadata,
    geometry=gpd.points_from_xy(
        min_value_date_with_metadata.longitude, min_value_date_with_metadata.latitude
    ),
)

min_value_date_with_metadata[
    "correct_utc"
] = min_value_date_with_metadata.value_date == pd.to_datetime("2018-01-01")

import matplotlib.pyplot as plt
from matplotlib import colors

cmap = colors.LinearSegmentedColormap.from_list("green_red_discrete", ["green", "red"])

# plot spatial distribution of utc time discrepancies
fig, ax = plt.subplots()

us_boundaries.plot(ax=ax, zorder=0)

min_value_date_with_metadata.plot(
    column="correct_utc",
    cmap=cmap,
    legend=True,
    markersize=1,
    categories=[True, False],
    ax=ax,
    zorder=1,
)

plt.show()

```

**Comment by aaraney** [comment]
It is not surprising that Arizona is correct, given the state does not use daylights savings time. It is worth noting that correctness appears (for this tiny sample) to be linked at the state level, it might be worth exploring this potential lead.

**Comment by jarq6c** [comment]
> It is not surprising that Arizona is correct, given the state does not use daylights savings time. It is worth noting that correctness appears (for this tiny sample) to be linked at the state level, it might be worth exploring this potential lead.

I'm guessing it's related to how each field office records their data and/or the local time used by their field equipment. As James suggested, I supposed we could report this upstream to USGS. But in the short term, I'll just have to keep this in mind when requesting data.

Thanks for putting this together! (-1 point for the color scheme though).
```python
plt.style.use('tableau-colorblind10')
cmap = colors.LinearSegmentedColormap.from_list("color_blind_discrete", ["C1", "C2"])
```
![Figure_1](https://user-images.githubusercontent.com/12818140/127560643-a0fe8679-572e-4d00-b97e-02a3c4b53313.png)

**Comment by aaraney** [comment]
> Thanks for putting this together! (-1 point for the color scheme though).

For sure! My apologies to the colorblind community, thanks for mentioning it and creating an inclusive map.

**Comment by james-d-brown** [comment]
@aaraney @jarq6c 

It is not perfectly inclusive because it doesn't cater to those of us with a principled objection to the color orange.

**Comment by jarq6c** [comment]
Follow-up: USGS feedback form seems to be broken.

**Comment by james-d-brown** [comment]
@jarq6c 

You could try Joe Nielsen (jnielsen@usgs.gov) who has helped me in the past w/ queries about NWIS, although I think he's fairly high up in the organization (Acting CPO or some such), so he may not reply immediately. I have other names too, but Joe is probably a good bet to either answer or forward.

**Comment by jkreft-usgs** [comment]
Hi folks-

I'm Jim Kreft, the product owner for the NWIS services referenced above, as well as next generation services that are currently in-flight and launching in beta soon.

Whether or not a location respects daylight savings time is indeed managed at the local office level, and harks back to a time when most of the users of the data were expected to be local cooperators, rather than national-scale data consumers.  At this point, attempting to put in a fix that is effectively a breaking change in this heavily used, already legacy API will probably break more workarounds than is worth it.   

Fortunately, the backing transactional data store and next generation services all work natively in UTC, hopefully obviating these problems in the future. 

If you have more questions, please reach out at jkreft@usgs.gov

**Comment by jarq6c** [comment]
@jkreft-usgs Thanks for the reply and additional insight!
