### ISSUE TITLE
HydroTools is trademarked

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#110]
Looks like we'll need to rename the package... again.

**Comment by jarq6c** [comment]
We'll leave the package name the same, but will update the banner to read "OWPHydroTools".

**Comment by aaraney** [comment]
Just now going through some old issues. @jarq6c can you include the entity that has this name trademarked? Depending on the context and products of the business, I do not think we will need to change the package name again. See the [What is a trademark?](https://www.uspto.gov/trademarks/basics/what-trademark) document by the U.S. Paten and Trademark office. Specifically,

> A common misconception is that having a trademark means you legally own a particular word or phrase and can prevent others from using it. However, you don’t have rights to the word or phrase in general, only to how that word or phrase is used with your specific goods or services.
>
> For example, let's say you use a logo as a trademark for your small woodworking business to identify and distinguish your goods or services from others in the woodworking field. This doesn't mean you can stop others from using a similar logo for non-woodworking related goods or services.

**Comment by jarq6c** [comment]
Yeah, it's in an entirely different domain: [https://hydrotoolsparts.com/](https://hydrotoolsparts.com/).

I changed the banner and references in documentation to make it more specific that this is DOC/NOAA/NWS/OWP hosted software, but the actual package name did not change.
