### ISSUE TITLE
Update nwis client to canonical format

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#117]
`nwis_client` returns a `value_date` column. We will add a `value_time_label="value_date"` option to continue this behavior.

Update 1: Add `value_time_label="value_date"` to `__init__` that will raise a deprecation warning. Default behavior will return `value_date`. `value_time_label="value_time"` will return `value_time`.

Update 2: Default behavior is `value_time_label="value_time"`. Warn if this option is not explicitly set by user.

Update 3: Default behavior is `value_time_label="value_time"` with no warning.

**Comment by jarq6c** [comment]
DeprecationWarning is suppresed by default. Changing to UserWarning.

**Comment by jarq6c** [comment]
Update 1 implemented in #118

**Comment by aaraney** [comment]
I think this might need to be reopened, @jarq6c. It appears that #185 did change the default value of `value_time_label` to `"value_time"` (Update 3.). However, `value_time_label` [still throws](https://github.com/jarq6c/hydrotools/blob/93850f8a1d665b642172f3df7022a7aef2db4d19/python/nwis_client/src/hydrotools/nwis_client/iv.py#L120) a `UserWarning` is a user passes `None` to `value_time_label` and then sets `value_time_label` to `"value_date"` not the, now canonical, `"value_time"`.

**Comment by jarq6c** [comment]
> I think this might need to be reopened, @jarq6c. It appears that #185 did change the default value of `value_time_label` to `"value_time"` (Update 3.). However, `value_time_label` [still throws](https://github.com/jarq6c/hydrotools/blob/93850f8a1d665b642172f3df7022a7aef2db4d19/python/nwis_client/src/hydrotools/nwis_client/iv.py#L120) a `UserWarning` is a user passes `None` to `value_time_label` and then sets `value_time_label` to `"value_date"` not the, now canonical, `"value_time"`.

Ah got me! I forgot about removing the warning!
