### ISSUE TITLE
Add gh-action to run unit tests marked slow at some regular interval

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/hydrotools#131]
Yeah good catch, I was not aware of that either. That sounds like something a `pytest --run-slow` should have caught. I need to create a new gh-action that runs our slow tests every Sunday if something new has been added since the last time the action ran.

_Originally posted by @aaraney in https://github.com/NOAA-OWP/hydrotools/issues/90#issuecomment-861621966_

**Comment by jarq6c** [comment]
Has this been resolved? It looks like slow tests have been running.

**Comment by aaraney** [comment]
Yes this has been resolved. Sorry, I should have closed this a long time ago.
