### ISSUE TITLE
Error in calling the nwis function for some of the catchments/station numbers

### ISSUE THREAD

**Issue by stcui007** [NOAA-OWP/hydrotools#133]
When running my python code, which extract USGS data for hydrograph, it works for most of the station sites. But occasionally, it fails for some of the station sites, and produces the following errors. The station sites that cause failure are:
station #: 
01189000
01010070
01017000
01015800
start date: "2015-12-01 00:00:00", end date: "2015-12-30 23:00:00" are all the same.
 ---
    
obs = nexus._hydro_location.get_data("2015-12-01 00:00:00", "2015-12-30 23:00:00")
  File "/home/shengting.cui/ngen-cal-test/ngen-cal/venv/lib/python3.8/site-packages/hypy/hydrolocation/nwis_location.py", line 50, in get_data
    return self._nwis.get(self._station_id, startDT=start, endDT=end)
  File "/home/shengting.cui/ngen-cal-test/ngen-cal/venv/lib/python3.8/site-packages/hydrotools/nwis_client/iv.py", line 262, in get
    dfs.loc[:, "value"] = pd.to_numeric(dfs["value"], downcast="float")
  File "/home/shengting.cui/ngen-cal-test/ngen-cal/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/shengting.cui/ngen-cal-test/ngen-cal/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'value'

**Comment by jarq6c** [comment]
Thanks Shengting.

I successfully reproduced the error with the following:

```python
from hydrotools.nwis_client.iv import IVDataService

service = IVDataService(value_time_label="value_time")
obs = service.get(
    sites=["01189000"],
    startDt="2015-12-01T00:00",
    endDt="2015-12-31T23:45"
)
```

The error seems to originate here:
https://github.com/NOAA-OWP/hydrotools/blob/908e00089cdd8c0f1d669fe21a454589c84ca78a/python/nwis_client/src/hydrotools/nwis_client/iv.py#L262

Looks like the issue is when NWIS returns an empty time series it results in an empty `pandas.DataFrame`. A `KeyError` is raised when the tool attempts to optimize the float values. As I recall, older versions of `nwis_client` would check for this using `pandas.DataFrame.empty` before attempting any optimizations. It looks like this functionality may have been lost during the `asyncio` transition.

I'll ping @aaraney for input.

**Comment by aaraney** [comment]
@stcui007, thanks for reporting this and thanks @jarq6c for verifying and reproducing the bug. I was able to reproduce it locally as well. I believe your thinking is correct @jarq6c, some logic was changed in #86. I will submit a PR and reference it here. Thanks!

**Comment by stcui007** [comment]
I have a check for empty dataframe in my code. When I get a returned empty
dataframe, I check for it and skip the step. For the reported case, the
function call doesn't come back so I can't check for it at my end.

**Comment by aaraney** [comment]
@stcui007, no worries. My apology if I implicitly suggested that you needed to do anything. This was just a bug in the software. #134 should resolve the issue.

**Comment by stcui007** [comment]
Hi Austin and Jason,
Thanks for spending time on resolving the issue. No apology is necessary as
I put in the test code before filing the ticket.

**Comment by jarq6c** [comment]
Fix has been deployed:
https://pypi.org/project/hydrotools.nwis-client/3.0.5/

@stcui007 @aaraney @hellkite500

**Comment by stcui007** [comment]
Thanks for working on this.
