### ISSUE TITLE
Jupyter Notebook RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#139]
# Duplicate
```python
from hydrotools.nwis_client.iv import IVDataService

data_service = IVDataService(value_time_label="value_time")
stage_df = data_service.get(
    sites=["01646500", "01013500"],
    startDT="2019-08-01",
    endDT="2019-09-01",
    parameterCd="00065"
)
```

Tagging @aaraney  for advice. It seems #100 fixed the issue in Google Collab, but it still persists in Jupyter Notebook and Spyder (which may have further issues with `asyncio`).

Running the code above inside a Jupyter Notebook or from Spyder resulted in `RuntimeError: This event loop is already running`.

# Fix
You can resolve the error by adding
```python
import nest_asyncio
nest_asyncio.apply()
```

**Comment by aaraney** [comment]
@jarq6c thanks for tagging me here. It looks like `hydrotools._restclient` version `3.0.4` from #130 was never published to pypi. I can take care of that and it should resolve the issue. We likely want to pin the `_restclient` version `nwis_client` is using to `>=3.0.4`.

**Comment by aaraney** [comment]
The new [`_restclient` version](https://pypi.org/project/hydrotools.-restclient/3.0.4/) is now up.

**Comment by aaraney** [comment]
I just verified that `3.0.4` resolves the issue in jupyter lab. I will open a PR to require `3.0.4` or higher in `nwis_client`!
