### ISSUE TITLE
Events package structure question

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/hydrotools#141]
I noticed while looking around the package today that the `event_detection` module is nested one level deeper than typical and does not have a parent subsubpackage (directory above with `__init__.py`).

More concretely, on the path `hydrotools/python/events/src/hydrotools/events/event_detection/`, there is an `__init__.py` in the `event_detection` directory but not in the `events` directory. @jarq6c can you clarify why this is the case? I assume there should be an `__init__.py` in the `events` directory as well.

Thanks!

**Comment by aaraney** [comment]
Do you have an opinion on the future of the `events` package? I am happy to retain it as it's own namespace package (as it is now). However, I am equally happy to keep it the way it is for flexibility in the future.

**Comment by jarq6c** [comment]
No _strong_ opinions at this point. My preference might be to leave it, unless there's a compelling reason to change it. I would rather future development guide what we do, say when/if different event based analysis methods get added like `events.event_analysis` or the like.
