### ISSUE TITLE
SSL Cert Verification Error

### ISSUE THREAD

**Issue by amaes3owp** [NOAA-OWP/hydrotools#150]
Good morning Jason - 
I moved my evaluations from one machine to another during the weekend and was able to run some evaluations. When using the nwis client I got the following error. 

ERROR: Unable to retrieve observations... EXITING: Cannot connect to host waterservices.usgs.gov:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')]

I can not send you the exact code but it was a simple call like the following:

>>> from hydrotools.nwis_client import IVDataService
>>> service = IVDataService()
>>> df = service.get(sites='01646500', startDT="2021-01-01", endDT="2021-02-01")

Any suggestions? 

Thanks!
Alex

**Comment by aaraney** [comment]
Not sure that this is related to #153, but it might be worth updating `_restclient` @amaes3owp.

Do the following to update:

```bash
pip install -U hydrotools._restclient
```

**Comment by amaes3owp** [comment]
Thank you guys for checking on this. Let me try it. I will also try to have a new clean python installation.

**Comment by jarq6c** [comment]
I was unable to duplicate this issue using the latest version of `hydrotools.nwis_client` and `hydrotools._restclient` deployed to a clean Python virtual environment on the same machine.

**Comment by aaraney** [comment]
That's good to hear @jarq6c. @amaes3owp, are you still facing an issue? Or can this be closed?

**Comment by amaes3owp** [comment]
I need a little more time to test.

**Comment by amaes3owp** [comment]
Here is my code:


import os
import pandas as pd

# Import Hydrotools module
from hydrotools.nwis_client.iv import IVDataService

def read_nwis_client():

    print("Reading ")
    service = IVDataService()
    df = service.get(sites='01646500', startDT='2021-01-01', endDT='2021-02-01')
    print(df.head())
    return df



# ---------------  MAIN --------------------
if __name__ == '__main__':

precip = read_nwis_client()

print('Program completed successfully')

I am still getting the error. I am reinstalling miniconda again and see if the problem goes away.

**Comment by jarq6c** [comment]
This snippet worked for me.

```python
import os
import pandas as pd
from hydrotools.nwis_client.iv import IVDataService

def read_nwis_client():
    print("Reading ")
    service = IVDataService()
    df = service.get(sites='01646500', startDT='2021-01-01', endDT='2021-02-01')
    print(df.head())
    return df

if __name__ == "__main__":
    precip = read_nwis_client()
    print('Program completed successfully')
```

**Comment by amaes3owp** [comment]
Good - 
Austin we did a test, then it seems that the issue is related to the miniconda installation. 
I am going to reinstall miniconda. 

We can close this ticket. 

Thanks!
Alex
