### ISSUE TITLE
Conversation: Use of `httpx`?

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#151]
@aaraney 

Opinions on this package?
https://www.python-httpx.org/

**Comment by aaraney** [comment]
This is the first I've heard of this package, so as of now, I don't have an opinion. That said, having looked through their docs, it seems like a hybrid between `requests` and `aiohttp`, although not as feature rich as `aiohttp`. 

To hopefully further the conversation, what is the motivation for the conversation? (That sounded a bit clinical, but I certainly don't mean it to come off that way ☕️😴). Are there features `httpx` offers that you are particularly interested in?

**Comment by jarq6c** [comment]
Closing. Discussion held at bi-weekly meeting. Neat package, don't necessarily need to switch our backends (especially since `nwm_client` will likely move to `fsspec`.
