### ISSUE TITLE
`nwis_client`: `SyntaxError`

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#153]
# Issue
`hydrotools.nwis_client` version 3.0.6 raises a `SyntaxError` on `import`.
@aaraney would you mind looking into this?
# Environment:
```console
Python 3.8.10 (default, Jun  4 2021, 15:09:15)
[GCC 7.5.0] :: Anaconda, Inc. on linux
```
# Duplicate
```python
import hydrotools.nwis_client
```
# Error
```console
'base_url:typing.Union[str, yarl.URL, NoneType]=None' of kind 'POSITIONAL_OR_KEYWORD' follows 'cache:CacheBackend=None' of kind 'KEYWORD_ONLY'
Traceback (most recent call last):
  File "/home/jason.regina/Projects/nwis_test/miniconda3/lib/python3.8/site-packages/aiohttp_client_cache/docs/forge_utils.py", line 32, in wrapper
    return revision(target_function)
  File "/home/jason.regina/Projects/nwis_test/miniconda3/lib/python3.8/site-packages/forge/_revision.py", line 330, in __call__
    next_.validate()
  File "/home/jason.regina/Projects/nwis_test/miniconda3/lib/python3.8/site-packages/forge/_signature.py", line 1344, in validate
    raise SyntaxError(
SyntaxError: 'base_url:typing.Union[str, yarl.URL, NoneType]=None' of kind 'POSITIONAL_OR_KEYWORD' follows 'cache:CacheBackend=None' of kind 'KEYWORD_ONLY'
```

**Comment by jarq6c** [comment]
Note: Encountered this error while trying to troubleshoot #150

**Comment by aaraney** [comment]
@jarq6c, thanks for bringing this to my attention. I will take a look at it.

**Comment by aaraney** [comment]
This looks like it might be a downstream issue with `aiohttp_client_cache`. I was able to reproduce the issue by just importing `aiohttp_client_cache`:

```python
import aiohttp_client_cache

> 'base_url:typing.Union[str, yarl.URL, NoneType]=None' of kind 'POSITIONAL_OR_KEYWORD' follows 'cache:CacheBackend=None' of kind 'KEYWORD_ONLY'
Traceback (most recent call last):
  File "/Users/araney/github/test_hydrotools/venv/lib/python3.8/site-packages/aiohttp_client_cache/docs/forge_utils.py", line 32, in wrapper
    return revision(target_function)
  File "/Users/araney/github/test_hydrotools/venv/lib/python3.8/site-packages/forge/_revision.py", line 330, in __call__
    next_.validate()
  File "/Users/araney/github/test_hydrotools/venv/lib/python3.8/site-packages/forge/_signature.py", line 1344, in validate
    raise SyntaxError(
SyntaxError: 'base_url:typing.Union[str, yarl.URL, NoneType]=None' of kind 'POSITIONAL_OR_KEYWORD' follows 'cache:CacheBackend=None' of kind 'KEYWORD_ONLY'
```

**Comment by aaraney** [comment]
I will try rolling back the version of `aiohttp-client-cache` and see if this resolves the issue. `v0.5.1` of `aiohttp-client-cache` was released on September 10, 2021 so I would have hoped that other tests would have caught this before then. Ill update the ticket with my findings shortly.

**Comment by aaraney** [comment]
I found that rolling back `aiohttp-client-cache` did not mitigate the issue. My guess is this is related to `aiohttp`'s October 31, 2021 release. Going to try rolling back `aiohttp` from `3.8.0`.

**Comment by aaraney** [comment]
pinning self opened issue [`aiohttp-client-cache` #103](https://github.com/JWCook/aiohttp-client-cache/issues/103)

**Comment by aaraney** [comment]
redeployed [`_restclient`](https://pypi.org/project/hydrotools.-restclient/3.0.5/) (see #154)

update using:

```python
pip install -U hydrotools._restclient
```

**Comment by aaraney** [comment]
I [heard back](https://github.com/JWCook/aiohttp-client-cache/issues/103#issuecomment-960026781_) from the maintainer of `aiohttp_client_cache`:

> Thanks for reporting! Looks like a new `base_url` param was added in https://github.com/aio-libs/aiohttp/pull/6129, and for some reason it's positional-or-keyword instead of keyword-only like the rest of the params. I'll get that fixed shortly.

**Comment by jarq6c** [comment]
Thanks for doing all the leg work!

**Comment by aaraney** [comment]
For sure! Have a nice evening!

**Comment by jarq6c** [comment]
Just confirming that the error was fixed on my end by updating `_restclient`
