### ISSUE TITLE
Package Request: Plotting Support

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#168]
This issue is for discussion of incorporating plotting utilities into `hydrotools`.

**Comment by jarq6c** [comment]
@aaraney

**Comment by jarq6c** [comment]
Recent events have highlighted the need to quickly generate hydrographs for arbitrary NWM channel features. I think this need could be fulfilled with a hypothetical `hydrotools.dashboard` subpackage that provides an interface to facilitate plotting capabilities for various `hydrotools` using a plugin architecture.

While `matplotlib` is the standard for publication quality static plots, I think `dash` and `plotly` are better suited for the above use-case. However, I can imagine a separate `hydrotools.plots` subpackage with some sort of "standard" matplotlibrc file meant to produce "publication quality" static plots.

In this case, "publication quality" implies standard figure dimensions, minimum 300 DPI, colorblind friendly pallets, and evidence-based recommendations for visualizing continuous and categorical data. We might also include defaults for non-journal use such as presentations, posters, or web-based formats.

**Comment by aaraney** [comment]
Can you elaborate a bit more on the distinction between `hydrotools.dashboard` and `hydrotools.plots`? I could insert assumptions here, but I won't for conversation sake. 

Other questions I have (we can probably punt these a little down the conversation):

- what is / are the intended target platforms / formats for this feature (i.e. web, gis, embedded in pdf)?
- are there requirements for plots to be interactive?
- who is / are the intended user of this API? A downstream web app developer (E.g. fastapi), a data scientist, or a practitioner?

**Comment by jarq6c** [comment]
Getting more specific: `dashboard` is a HydroTools GUI. `plots` is a HydroTools Python plotting API.

**Comment by aaraney** [comment]
Thanks for elaborating. I am starting to see more of your vision. I have few clarifying questions:

> `hydrotools.dashboard` could be the primary GUI intended to expose basic functionality of various tools.

1. What do you have in mind when you say GUI? A web app? A literal GUI (e.g. PyQt5)? A console UI (e.g. [`rich`](https://github.com/Textualize/rich))
2. Do you envision the dashboard to be installed and used primarily on end-users hardware? Or will are you thinking this could be configured and deployed as a service?

**Comment by jarq6c** [comment]
I was thinking a web app using a framework like [dash](https://dash.plotly.com/). I think this would be easier to maintain than a full fat GUI, especially with a plugin architecture. This would also allow some flexibility for deployment. The dashboard could be used locally or deployed as a service, though deployment details would be left to users (refer to the documentation on deploying dash apps https://dash.plotly.com/deployment).

**Comment by aaraney** [comment]
That makes sense. I like that idea. How configurable are you thinking the software would be? Specify the the panels or components you would like to have in some kind of configuration file? So maybe a yaml file or something that determines what dashboard components you want and their data sources?

**Comment by jarq6c** [comment]
The TEEHR project (https://github.com/RTIInternational/teehr) is actively developing Python/Notebook based visualization solutions to support CIROH researchers.
