### ISSUE TITLE
As ROE user, I am getting a file that cache nwis data in my working folder that is collapsing the system. 

### ISSUE THREAD

**Issue by amaes3owp** [NOAA-OWP/hydrotools#173]
Hello guys!
I have a brand new installation of miniconda3 (version 3.8) on a new system. I am calling the IV module to retrieve NWIS data and see a file in my working folder called: 

 /[working_folder]/nwisiv_cache.sqlite

How can I tell the program that I want that file in an specific location (i.e. /home)?
I do not want this huge file to affect my system, where is this file installed by default?

Thanks!
Alex

**Comment by jarq6c** [comment]
@aaraney It appears there may be some unexpected behavior here.

# Example
```python
# Import the NWIS IV Client
from hydrotools.nwis_client.iv import IVDataService
from pathlib import Path
from time import sleep

# Default cache
cache = Path("nwisiv_cache.sqlite")

# Retrieve data from a single site
service = IVDataService(
    cache_expire_after=1,
    value_time_label="value_time"
)

# First call
observations_data = service.get(
    sites='01646500',
    startDT='2019-08-01',
    endDT='2020-08-01'
    )
sz = cache.stat().st_size
print(f"First call: {sz}")
sleep(2.0)

# Second call
observations_data = service.get(
    sites='01646500',
    startDT='2019-10-01',
    endDT='2020-06-01'
    )
sz = cache.stat().st_size
print(f"Second call: {sz}")
sleep(2.0)

# Third call
observations_data = service.get(
    sites='01646500',
    startDT='2019-12-01',
    endDT='2020-04-01'
    )
sz = cache.stat().st_size
print(f"Third call: {sz}")
```

# Output
```console
First call: 2764800
Second call: 4583424
Third call: 5505024
```

# Expected behavior
With such a short `cache_expire_after` parameter, I would expect the size of the cache to decrease over time. However, it appears the cache only increases.

**Comment by amaes3owp** [comment]
Here is the code I am using:


# Retrieve USGS Observations using nwis

def ised_event_get_usgs_observations_nwis(usgs_stations_list, startDT, endDT):

    # delete any station where the USGS code is None
    usgs_stations_list = [x for x in usgs_stations_list if x is not None]
    usgs_stations_append = []
    chunk = 1

    for i in range(0, len(usgs_stations_list), chunk):
        usgs_stations_list_tmp = ','.join('%s' % txt for txt in usgs_stations_list[i:i + chunk])
        try:
            # Retrieve data

            measurements = nwis.get_record(sites=usgs_stations_list_tmp, service='iv',
                                           start=startDT,
                                           end=endDT
                                           )
            measurements = measurements.reset_index(level=[0])
            measurements['usgs_site_code'] = usgs_stations_list_tmp

            # renaming and selecting relevant columns
            measurements = measurements.rename(columns={
                "datetime": "value_date",
                "00060": "value"
            })

            measurements = measurements[["usgs_site_code", "value_date", "value"]]

            measurements['value_date_UTC'] = pd.to_datetime(measurements['value_date'], format='%Y-%m-%dT%H:%M:%S.%f%z')
            measurements['value_date_UTC'] = pd.to_datetime(measurements['value_date_UTC'], utc=True)
            measurements['value_date'] = measurements['value_date_UTC'].dt.strftime('%Y-%m-%dT%H:%M:%SZ')

            measurements = measurements[["usgs_site_code", "value_date", "value"]]

            usgs_stations_append.append(measurements)
        except Exception as err:
            print('ERROR: Unable to retrieve observations... EXITING: ' + str(err))
    usgs_stations_list_df = pd.concat(usgs_stations_append, ignore_index=True, sort=False).sort_values(
        by=(['usgs_site_code', 'value_date'])
    )

    return usgs_stations_list_df

**Comment by amaes3owp** [comment]
Great - 
I see that I can define where to store the cache file. 
I will update the code. 

Thanks!

**Comment by amaes3owp** [comment]
here is the function without cache



    # receives a list of stations and creates a dataframe with all the observations
def ised_event_get_usgs_observations(usgs_stations_list, startDT, endDT):


    # delete any station where the USGS code is None
    usgs_stations_list = [x for x in usgs_stations_list if x is not None]
    usgs_stations_append = []
    chunk = 10
    service = IVDataService(enable_cache=False)
    for i in range(0, len(usgs_stations_list), chunk):
        usgs_stations_list_tmp = ','.join('%s' % txt for txt in usgs_stations_list[i:i + chunk])
        try:
            #Retrieve data
            measurements = service.get(sites=usgs_stations_list_tmp,
                                             parameterCd='00060',
                                             startDT=startDT,
                                             endDT=endDT)

            usgs_stations_append.append(measurements)
        except Exception as err:
            print('ERROR: Unable to retrieve observations... EXITING: ' + str(err))
    usgs_stations_list_df = pd.concat(usgs_stations_append, ignore_index=True, sort=False).sort_values(
        by=(['usgs_site_code', 'value_date'])
    )

    return usgs_stations_list_df

**Comment by jarq6c** [comment]
@amaes3owp Did disabling the cache resolve your issue?

**Comment by amaes3owp** [comment]
Good Morning Jason!

Yes! I disable the cache and I do not have the file anymore. However, I would be interested in using this option in the near future.

Are you guys checking if the size of the cache file is getting stable? Can I decide where to save the cache file? I see that in the code you have default cache --> cache=Path('XX')
is that the way to tell the function where to save the file?

**Comment by aaraney** [comment]
@jarq6c and @amaes3owp,

Thanks for the on-going dialog. @amaes3owp i'd not thought about your use case when I first wrote the software, but I wholeheartedly agree with you that the cache path should be configurable. Once I resolve #175 I will link the status of that ticket here.

Tangentially, @jarq6c, regarding:

> With such a short cache_expire_after parameter, I would expect the size of the cache to decrease over time. However, it appears the cache only increases.

I am not sure when cache reclamation occurs. I don't think it would make sense to delete once the cache has gone stale though. Ill go digging for an answer quickly.

**Comment by jarq6c** [comment]
> From the [`aiohttp-client-cache` documentation](https://aiohttp-client-cache.readthedocs.io/en/latest/user_guide.html#removing-expired-responses):
> 
> > For better performance, expired responses won’t be removed immediately, but will be removed (or replaced) the next time they are requested. To manually clear all expired responses, use [CachedSession.delete_expired_responses()](https://aiohttp-client-cache.readthedocs.io/en/latest/aiohttp_client_cache.session.html#aiohttp_client_cache.session.CachedSession.delete_expired_responses)
> 
> Im happy to expose a public method that allows you to manually clear the cache. Likewise, if we wanted to come up with a cache reclamation policy (we try to clear the cache after `n` calls or something like that), I am all ears.

Let's discuss. My inclination is that we have too many definitions/expectations for what "caching" does.

**Comment by jarq6c** [comment]
> @aaraney Thank you for working on this on the new ticket. I think I will enable the cache when #175 is complete. About the cache, in my case I have a moving window that adds the most recent observation data and deletes the observations that are 60 days older or more. Can the cached sessions work like that? at the end we will have a stable cache file that keeps its size.

@amaes3owp The basic caching built into `nwis_client` works more like the caching your Internet browser would use. More advanced caching functionality like what you're describing could be implemented in `hydrotools.cache` subpackage that focuses on caching from the data/DataFrame point of view. However, this package's features are still quite limited.

**Comment by jarq6c** [comment]
Closing. We'll circle back to increased caching functionality on a different issue.
