### ISSUE TITLE
contingency_table computed from compute_contingency_table doesn’t contain both True and False for the observed or the simulated series 

### ISSUE THREAD

**Issue by xfeng2021** [NOAA-OWP/hydrotools#183]
The following line in function compute_contingency_table:

ctab = pd.crosstab(observed, simulated, dropna=False) 
produces ctab containing only True or False for either the observed or the simulated series? It would cause the error in ctab.loc. 

Could you add a solution to handle such situation?

**Comment by jarq6c** [comment]
Verified if either of the input categorical series contain only `True` or `False`, then `compute_contingency_table` fails with a `KeyError` for the missing boolean category.
