### ISSUE TITLE
"Run Slow Unit Tests" Action has been failing for some time

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/hydrotools#217]
As @jarq6c mentioned in #216, the "Run Slow Unit Tests" Action has been failing for some time. I did a little bit of digging and the issue is twofold. First, the `svi_client` is missing a testing dependency, `pytest-aiohttp`. We use this dependecny in `_restclient` and `nwis_client` to provide an `asyncio` loop to tests. This is the cause of the `RuntimeError: There is no current event loop in thread 'MainThread'.` errors in the slow unit tests. Second, in general the `svi_client` integration tests are a little brittle. We end up hitting an esri feature server repeatedly upwards of 600 times. If requests are made too quickly, the server just rejects the requests.

**Comment by jarq6c** [comment]
Do we need to hit an ESRI server 600 times?

**Comment by aaraney** [comment]
@jarq6c, no and that would remedy this. I think just hitting each endpoint is enough.
