### ISSUE TITLE
SVI Client slow unit tests failing

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#228]
Looks like `svi_client` slow unit tests are failing. May want to check it out, time permitting.

**Comment by jarq6c** [comment]
I get this error when using the example from the README.md:
```console
pydantic_core._pydantic_core.ValidationError: 5 validation errors for FieldNameMap
socioeconomic_value
  Field required [type=missing, input_value={'state_name': 'STATE_NAM...TP', 'svi_rank': 'USTP'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
household_comp_and_disability_value
  Field required [type=missing, input_value={'state_name': 'STATE_NAM...TP', 'svi_rank': 'USTP'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
minority_status_and_lang_value
  Field required [type=missing, input_value={'state_name': 'STATE_NAM...TP', 'svi_rank': 'USTP'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
housing_type_and_trans_value
  Field required [type=missing, input_value={'state_name': 'STATE_NAM...TP', 'svi_rank': 'USTP'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
svi_value
  Field required [type=missing, input_value={'state_name': 'STATE_NAM...TP', 'svi_rank': 'USTP'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
```

**Comment by jarq6c** [comment]
I'm assuming this means that something about the SVI service endpoints must have changed and broke the client.

**Comment by jarq6c** [comment]
If anyone happens across this issue, you can still manually download the data from this page:
https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html

**Comment by aaraney** [comment]
> I'm assuming this means that something about the SVI service endpoints must have changed and broke the client.

Oh, that's not good. @jarq6c, im looking into this now.

**Comment by aaraney** [comment]
Im going to open a separate issue to track this.

**Comment by aaraney** [comment]
re-running the slow `svi_client` unit tests now. #241 should fix the issue. However, the `nwis_client` tests will continue to fail until a new version of `_restclient` is pushed to `pypi`. This is currently not possible b.c. https://github.com/pypi/warehouse/issues/14806.

**Comment by aaraney** [comment]
I just re-ran the slow tests and they [now pass](https://github.com/NOAA-OWP/hydrotools/actions/runs/6669996925)!
