### ISSUE TITLE
Determine feasibility of _restclient's continued dependence on `aiohttp_cache_client`

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/hydrotools#238]
See #237, specifically [this comment](https://github.com/NOAA-OWP/hydrotools/pull/237#issuecomment-1733935850). The long and short of it is a transitive dependency of `_restclient` may require `_restclient.RestClient` to change its public api. That is not desirable and likely not feasible. `_restclient` may need to change caching providers to avoid public api changes.

**Comment by jarq6c** [comment]
Thanks for following up on this Austin. Just to clarify, would this issue cause `nwis_client` to fail when running for the first time with a "no event loop in the Main thread" error?

**Comment by aaraney** [comment]
@jarq6c, I dont believe so. I think the program wont exit.
