### ISSUE TITLE
question about update cycle for hydrotools

### ISSUE THREAD

**Issue by andywood** [NOAA-OWP/hydrotools#248]
Will hydrotools be updated to stay current as the hydrofabric and products change?  The included routelink files are somewhat out of date now (3 years) and don't include AK or v3.x.  Or is this repo being superseded or complemented by newer OWP evaluation capability codes/repos?  If so it might be useful to include a section in the landing-page README for 'Related Capabilities' to point to the other repos.

**Comment by jarq6c** [comment]
I'm currently in the process of updating the `nwm_client_new` package to retrieve operational forecasts from the expanded domain in v3.0.7. Note that the routelink files did not change significantly for three years (v2.1.6 was identical to v2.2.3). The routelink was updated on NOMADS in August 2023 without much fanfare, and the NWM v3.0 model output stream wasn't stable for over a month.

The `hydrotools` source files on HydroShare have been updated: https://www.hydroshare.org/resource/e9fe66730d184bdfbaea19639bd7cb55/

All that remains is to update the software side. I'll update here once that's done (hopefully, next week).

With regard to the hydrofabric and v4.0/NGEN modeling output: It remains unclear to what extent, if any, `hydrotools` will support the new output. Theoretically, future versions of the NWM will generate similar or identical output to what is produced now, but as of today we have no official word on that, nor any official support for `hydrotools` as a user of current or future model output.

**Comment by andywood** [comment]
Hi Jason, amazing, you may have set a record for speed of response to an issue (and on a Saturday no less)!  Thanks for the insights and the link.  The NextGen HF still has some development ahead so it makes sense that this doesn't connect with that yet.

**Comment by jarq6c** [comment]
Thanks for reporting this issue @andywood 

The `nwm_client_new` package is now compatible with the expanded domain. You can find examples on PyPI:
https://pypi.org/project/hydrotools.nwm-client-new/7.4.0/
