### ISSUE TITLE
Trying to gather historical NWS gage measurements instead of forecast for a given station

### ISSUE THREAD

**Issue by samakraus** [NOAA-OWP/hydrotools#256]
Hello, I'm interested in collecting measured data for a given NWS streamgage. The code for ```hydrotools.nwm_client_new``` seems like it would be able to do this, but its examples only present how to gather forecast data. Is there a simple way to change the ```get()``` function inputs to instead download the actual measured data for the same type of gage?

**Comment by aaraney** [comment]
Hi @samakraus! Thanks for reaching out with the question. To my knowledge, NWS does not maintain or operate stream gages. I think you are looking for USGS stream gage observation data? Many NWM or NWS forecast points coincide with USGS gage locations. It might be easiest to see this by visiting https://water.noaa.gov, selecting a point on the map, and scrolling down in the right most panel until you find under the Gage Info section `USGS`.

If that is the case, the [`hydrotools.nwis_client`](https://github.com/NOAA-OWP/hydrotools/tree/main/python/nwis_client) or [USGS's `dataretreival` package](https://github.com/DOI-USGS/dataretrieval-python) may fit your needs. They both retrieve real time or historical observations. The `hydrotools.nwis_client` is suited for gather large amount of data (e.g. CONUS observations) while `dataretrieval` is general purpose and more feature rich.

**Comment by aaraney** [comment]
For sure!

> I followed your suggestion, but it seems there is no USGS affiliation for the specific gauge I'm interested in - NWSLI: BFCN7, Reach ID: 22164238 (Bat Fork Creek near Hendersonville)

Well I guess you learn something new everyday! You were right, it looks like NWS does operate gauges. I threw together a client using the docs from https://api.water.noaa.gov/nwps/v1/docs/ as guidance that should let you retrieve, at least, some of the data you are interested. I don't see an option to specify a date range, so this will not suffice if you need historical data.

<details><summary><code>get_stageflow_product</code> client</summary>

For consistency the "client" follows the `hydrotools` canonical dataframe format.

Requires `pandas` and `requests` be installed.


```python
from __future__ import annotations

from typing import Literal

import numpy as np
import pandas as pd
import requests

_BASE_URl = "https://api.water.noaa.gov"


def get_stageflow_product(
    identifier: str, product: Literal["observed", "forecast"]
) -> pd.DataFrame:
    url = f"{_BASE_URl}/nwps/v1/gauges/{identifier}/stageflow/{product}"
    req = requests.get(url)
    assert req.ok
    data = req.json()

    df = pd.DataFrame.from_records(data["data"], exclude=["secondary", "generatedTime"])

    df.rename(columns={"validTime": "value_time", "primary": "value"}, inplace=True)
    df["value"] = pd.to_numeric(df["value"], downcast="float")
    df["value_time"] = pd.to_datetime(df["value_time"])

    mask = np.zeros(len(df), dtype="int32")
    df["nws_lid"] = pd.Categorical.from_codes(mask, categories=[identifier])
    df["variable_name"] = pd.Categorical.from_codes(mask, categories=["stage height"])
    df["measurement_unit"] = pd.Categorical.from_codes(
        mask, categories=[data["primaryUnits"].lower()]
    )

    column_order = [
        "value_time",
        "variable_name",
        "nws_lid",
        "measurement_unit",
        "value",
    ]

    return df[column_order]


if __name__ == "__main__":
    df = get_stageflow_product("BFCN7", "observed")
```

</details>

> Related, do you know if there is an easy way to change the `hydrotools.nwis_client` output to give stage instead of volumetric flow rate for the output dataframe?

Yes! Just change `get`'s parameter `parameterCd="00065"` and you will get stage height instead.

```python
from hydrotools.nwis_client import IVDataService
client = IVDataService()
df = client.get(sites="0344632850", parameterCd="00065")

```

**Comment by samakraus** [comment]
@aaraney brilliant thank you! These do just what I'm looking for!
