### ISSUE TITLE
Update automated testing

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#259]
Python 3.8 is EOL as of 2024-10-07. We need to update the automated tests and PyPI classifiers of all packages. I'm thinking we should target the three versions that are out of "bugfix" status and 3.12 (the oldest version still in bugfix).

**Comment by jarq6c** [comment]
I'll do each subpackage one at a time and address issues as needed.

**Comment by aaraney** [comment]
Agreed! We should use this opportunity to move package metadata fully to [`pyproject.toml`](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) also.

**Comment by jarq6c** [comment]
Leaving this open until we get to .github/workflows/run_slow_unit_tests.yml
