### ISSUE TITLE
Add examples and procedure for adding future examples to repo

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/hydrotools#46]
For the benefit of users, it makes sense to demonstrate example usages of `evaluation_tools` sub-packages. As of now, examples are provided in docstrings and readme's. This form of documentation is suitable for quick reference, however there is a need for more complete example style documentation.

@jarq6c has [written a great example](https://github.com/jarq6c/little_hope) detailing peak flow analysis for [little hope creek](https://waterdata.usgs.gov/nc/nwis/inventory/?site_no=02146470&agency_cd=USGS). This example is expected to be the first added to the repo and in doing so, pave the way for future examples. That being said, once added to the repo, the little hope example should serve as an example for future example additions.

## Outcomes of this addition
- Maintain multiple ways for a user to find example content as well as interact with it
- Require that examples take on the form of jupyter notebooks as well as a standalone python script. This should allow a user to complete the example in browser via a google colab notebook, locally in jupyter, or locally via python.
- In support of users who are not as git savy or just want the example material, each example should be downloadable in a zipped format, as well as, the unzipped form. This will likely be taken care of by a github action, meaning the example developer does not have to worry about maintaining/versioning zipped examples.
- Display completed notebook examples in gh-pages deployment with the ability to open the example in google colab. 

## Example structure expectation
1. Each example should sit under `/examples/<name-of-example>` 
1. Contain a README (`/examples/<name-of-example>/README.md`) that:
    1. briefly gives an overview of the example
    1. mentions the ways to interact with the example and links to google colab (google colab, local jupyter, local standalone)
    1. outlines the local installation process
    1. outlines how to run the standalone version
1. Includes a jupyter notebook with the same name as the example.
1. Includes a standalone python script with the same name as the example.
1. Includes a `requirements.txt` file for installing reproducible dependencies.
1. (this may change in the future) contains a zipped file of all the above.

**Comment by jarq6c** [comment]
Very nice! Thanks for getting this started.

**Comment by aaraney** [comment]
> Very nice! Thanks for getting this started.

For sure. I got everything working locally, however to get the notebooks into the gh-pages deployment without a hacky solution, I had to open a PR to the [nbsphinx-link](https://github.com/vidartf/nbsphinx-link) project. In short, `nbsphinx` (the parent package to `nbsphinx-link`) converts jupyter notebooks to restructured text files that sphinx can render as html. In the aforementioned example directory structure, all notebook files would live outside of the `sphinx` `docs` directory. This is a problem, because `sphinx` "doesnt know" about files that live above the `docs` dir and `nbsphinx` does not have a way to link to notebook files outside of the `docs` dir. `nbsphinx-link` is the solution to this problem, however as the project sits now, you would have to have a config file for each notebook in `/examples`. This seems unnecessarily redundant. The maintainer, mentioned in a prior issue that they would be open to a PR that introduced that kind of functionality, so hopefully they will accept the change and we can use it to deploy notebooks in the project. If not, we can just use the fork I have or something like that.

**Comment by aaraney** [comment]
Just an update to this issue. There has been no feedback or communication over the [PR](https://github.com/vidartf/nbsphinx-link/pull/15) I put in on the `nbsphinx-link` project. Hoping that will change soon.

**Comment by aaraney** [comment]
Just another update. The PR that I referenced in the previous comment still has not been attended to, so instead, in my personal time, Ive repackaged and published by forked version on PYPI under the name [nbsphinx-multilink](https://pypi.org/project/nbsphinx-multilink/). We can now pull this in as a dependency for displaying notebooks in sphinx.

**Comment by aaraney** [comment]
Im going to wait to make this addition until #57 has been merged.

**Comment by aaraney** [comment]
Given the state of #88, I am going to close this for now. We can reopen for continued discussion in the future.
