### ISSUE TITLE
As a developer, I would like to specify development dependencies at the subpackage level

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/hydrotools#79]
At the moment, all development deps are installed at the namespace package level, namely `pytest`. I would like to come to an agreed upon standard for specifying development deps to `setuptools`. Below are two examples `setup.py` file implementations that solve this problem:

1.
```python
# file: setup.py

from setuptools import setup
from setuptools.command.develop import develop
import subprocess

DEVELOPMENT_REQUIREMENTS = ["pytest"]

# Development installation
class Develop(develop):
    def run(self):
        # Install development requirements
        for dev_requirement in DEVELOPMENT_REQUIREMENTS:
            subprocess.check_call(
                [sys.executable, "-m", "pip", "install", dev_requirement]
            )
        develop.run(self)

setup(
    name="mypackage",
    description="some package that does something",
    install_requires=["pandas"],
    cmdclass={"develop": Develop},
)
```

The above is used as such, `python setup.py develop`. This will install all the deps, development deps, and the package in an "editable" form (i.e. like `pip install -e  .`).

2. 
```python
# file: setup.py

from setuptools import setup

DEVELOPMENT_REQUIREMENTS = ["pytest"]

setup(
    name="mypackage",
    description="some package that does something",
    install_requires=["pandas"],
    extras_require={"develop" : DEVELOPMENT_REQUIREMENTS},
)
```

2 is used as follows, `pip install -e ".[develop]"` (the quotes are not required in bash, but are required in zsh and likely other shells).

Personally, I prefer the second option over the first. The second option uses `pip` and thus files like `pyproject.toml` are regarded, whereas in 1, they are not. Likewise, this functionality should work on `pypi`, I am unsure at this moment how you would specify to include tests in the package though, so that may be a moot point. The second solution is also far less code and more maintainable across subpackages IMO.

**Comment by aaraney** [comment]
@jarq6c can you weigh in on this with your opinion?

**Comment by jarq6c** [comment]
Based on a cursory exploration of the current Python packaging landscape, I'm also partial to option 2. This will move us in the direction of explicitly leaning on `pip` to handle packaging for any purpose (development, release, etc).

**Comment by aaraney** [comment]
I agree moving under the umbrella of `pip` should only help us as `hydrotools` grow. I will open a PR and ref it here moving all subpackages under option 2 in due time. Ill leave this open to track the progress though and document any snags that occur.
