### ISSUE TITLE
stateCd does not work with nwis_client

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/hydrotools#90]
I had not realized certain options were non-functional with the current version of `nwis_client`. These options appear to work with the version on the `restclient_transition` branch. So, I would say that makes getting this branch merged into main a high priority.

**Comment by aaraney** [comment]
Yeah good catch, I was not aware of that either. That sounds like something a `pytest --run-slow` should have caught. I need to create a new gh-action that runs our slow tests every Sunday if something new has been added since the last time the action ran.

**Comment by aaraney** [comment]
Something similar to [this](https://stackoverflow.com/a/67527144).
