### ISSUE TITLE
nwis-client latest builds broken when installed on Python 3.6

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/hydrotools#98]
Importing the latest nwis-client using python 3.6
``` python
from hydrotools.nwis_client.iv import IVDataService
```
fails with 
```
TypeError: 'type' object is not subscriptable
```

The error may be more ubiquitous than just the IVDataService import, but that is where [we have had trouble with it](https://github.com/NOAA-OWP/t-route/blob/82e7e62d74ac1ec8e876932921cb42adf31006e4/src/python_routing_v02/troute/routing/diffusive_utils.py#L350). 

A brief conversation with the developers suggested that a down stream dependency forces a bump to python 3.7 as the minimum requirement and they are considering workarounds to allow backward compatibility. The newer version is worth the effort, with order-of-magnitude faster retrieval speeds from the NWIS service. We do not have any real reason to continue using 3.6, so we may look at an upgrade path.

#### Workaround
For now, uninstalling the nwis-client, -restclient, and events modules
``` sh
pip uninstall hydrotools.nwis_client
pip uninstall hydrotools.-restclient
pip uninstall hydrotools.events
```
then reinstalling the following versions allowed us to continuing using the service in the meantime on python 3.6.8 
``` sh
pip install hydrotools.-restclient==2.0.0a0
pip install hydrotools.nwis-client==2.0.0a0
```

**Comment by aaraney** [comment]
@jameshalgren, having briefly looked into the dependencies required by the `nwis_client`, namely `hydrotools._restclient` which is causing this issue, it will not be feasible to roll back and support python 3.7. The package `aiohttp` which both the `nwis_client` and `_restclient` are highly dependent on requires `>= 3.7`. I tracked down the [git blame](https://github.com/aio-libs/aiohttp/pull/5278) for this decision by the `aiohttp` developers and they cited the python version lifecycle as the reason for dropping support for `<=3.6`. In short, python 3.6's end of life (EOL) is 2021-12-23.

My apologies for miss leading you in our earlier conversation, I was unaware of python version requirement in the `aiohttp` package.

**Comment by jarq6c** [comment]
FTR: Even before I was aware of `aiohttp`'s decision, I was opposed to backwards compatibility with 3.6. The EOL justification is nice to cite though. Thanks @aaraney

**Comment by jameshalgren** [comment]
All this is consistent with our plan to separate the data handling code from the processing code. Thank you for the additional information.
